#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20

//map1-1
#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPA	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BACKGROUNDTILE 6
#define OBJECT_TYPE_PIPE 7
#define OBJECT_TYPE_QUESTION_BRICK 8
#define OBJECT_TYPE_SPECIAL_PLATFORM 9
#define OBJECT_TYPE_LEAF 10
#define OBJECT_TYPE_FIREVENUSTRAP 11
#define OBJECT_TYPE_FIREBALL 12
#define OBJECT_TYPE_SPECIAL_BRICK 13
#define OBJECT_TYPE_SPECIAL_BUTTON 14
#define OBJECT_TYPE_BLOCKKOOPA 15

#define OBJECT_TYPE_CARD 20

//world map
#define OBJECT_TYPE_LANDSCAPE 25
#define OBJECT_TYPE_PATH 35
#define OBJECT_TYPE_NODE 40


#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000

////big
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)

#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_BIG_HOLD (ID_SPRITE_MARIO_BIG+700)
#define ID_SPRITE_MARIO_BIG_HOLD_LEFT (ID_SPRITE_MARIO_BIG_HOLD+10)
#define ID_SPRITE_MARIO_BIG_HOLD_RIGHT (ID_SPRITE_MARIO_BIG_HOLD+20)

#define ID_SPRITE_MARIO_BIG_KICK (ID_SPRITE_MARIO_BIG+800)
#define ID_SPRITE_MARIO_BIG_KICK_LEFT (ID_SPRITE_MARIO_BIG_KICK+10)
#define ID_SPRITE_MARIO_BIG_KICK_RIGHT (ID_SPRITE_MARIO_BIG_KICK+20)

#define ID_SPRITE_MARIO_BIG_WORLDMAP (ID_SPRITE_MARIO_BIG+990)



///die
#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

///small
#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#define ID_SPRITE_MARIO_SMALL_HOLD (ID_SPRITE_MARIO_SMALL+700)
#define ID_SPRITE_MARIO_SMALL_HOLD_LEFT (ID_SPRITE_MARIO_SMALL_HOLD+10)
#define ID_SPRITE_MARIO_SMALL_HOLD_RIGHT (ID_SPRITE_MARIO_SMALL_HOLD+20)

#define ID_SPRITE_MARIO_SMALL_KICK (ID_SPRITE_MARIO_SMALL+800)
#define ID_SPRITE_MARIO_SMALL_KICK_LEFT (ID_SPRITE_MARIO_SMALL_KICK+10)
#define ID_SPRITE_MARIO_SMALL_KICK_RIGHT (ID_SPRITE_MARIO_SMALL_KICK+20)

#define ID_SPRITE_MARIO_SMALL_WORLDMAP (ID_SPRITE_MARIO_SMALL+990)


///tail
#define ID_SPRITE_MARIO_TAIL (ID_SPRITE_MARIO + 4000)
#define ID_SPRITE_MARIO_TAIL_IDLE (ID_SPRITE_MARIO_TAIL + 100)
#define ID_SPRITE_MARIO_TAIL_IDLE_LEFT (ID_SPRITE_MARIO_TAIL_IDLE + 10)
#define ID_SPRITE_MARIO_TAIL_IDLE_RIGHT (ID_SPRITE_MARIO_TAIL_IDLE + 20)

#define ID_SPRITE_MARIO_TAIL_WALKING (ID_SPRITE_MARIO_TAIL + 200)
#define ID_SPRITE_MARIO_TAIL_WALKING_LEFT (ID_SPRITE_MARIO_TAIL_WALKING + 10)
#define ID_SPRITE_MARIO_TAIL_WALKING_RIGHT (ID_SPRITE_MARIO_TAIL_WALKING + 20)
#define ID_SPRITE_MARIO_TAIL_RUNNING (ID_SPRITE_MARIO_TAIL + 300)
#define ID_SPRITE_MARIO_TAIL_RUNNING_LEFT (ID_SPRITE_MARIO_TAIL_RUNNING + 10)
#define ID_SPRITE_MARIO_TAIL_RUNNING_RIGHT (ID_SPRITE_MARIO_TAIL_RUNNING + 20)
#define ID_SPRITE_MARIO_TAIL_JUMP (ID_SPRITE_MARIO_TAIL + 400)
#define ID_SPRITE_MARIO_TAIL_JUMP_WALK (ID_SPRITE_MARIO_TAIL_JUMP + 10)
#define ID_SPRITE_MARIO_TAIL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_TAIL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_TAIL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_TAIL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_TAIL_JUMP_RUN (ID_SPRITE_MARIO_TAIL_JUMP + 20)
#define ID_SPRITE_MARIO_TAIL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_TAIL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_TAIL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_TAIL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_TAIL_SIT (ID_SPRITE_MARIO_TAIL + 500)
#define ID_SPRITE_MARIO_TAIL_SIT_LEFT (ID_SPRITE_MARIO_TAIL_SIT + 10)
#define ID_SPRITE_MARIO_TAIL_SIT_RIGHT (ID_SPRITE_MARIO_TAIL_SIT + 20)

#define ID_SPRITE_MARIO_TAIL_BRACE (ID_SPRITE_MARIO_TAIL + 600)
#define ID_SPRITE_MARIO_TAIL_BRACE_LEFT (ID_SPRITE_MARIO_TAIL_BRACE + 10)
#define ID_SPRITE_MARIO_TAIL_BRACE_RIGHT (ID_SPRITE_MARIO_TAIL_BRACE + 20)

#define ID_SPRITE_MARIO_TAIL_HOLD (ID_SPRITE_MARIO_TAIL+700)
#define ID_SPRITE_MARIO_TAIL_HOLD_LEFT (ID_SPRITE_MARIO_TAIL_HOLD+10)
#define ID_SPRITE_MARIO_TAIL_HOLD_RIGHT (ID_SPRITE_MARIO_TAIL_HOLD+20)

#define ID_SPRITE_MARIO_TAIL_KICK (ID_SPRITE_MARIO_TAIL+800)
#define ID_SPRITE_MARIO_TAIL_KICK_LEFT (ID_SPRITE_MARIO_TAIL_KICK+10)
#define ID_SPRITE_MARIO_TAIL_KICK_RIGHT (ID_SPRITE_MARIO_TAIL_KICK+20)

#define ID_SPRITE_MARIO_TAIL_FLY (ID_SPRITE_MARIO_TAIL+900)
#define ID_SPRITE_MARIO_TAIL_FLY_LEFT (ID_SPRITE_MARIO_TAIL_FLY+10)
#define ID_SPRITE_MARIO_TAIL_FLY_RIGHT (ID_SPRITE_MARIO_TAIL_FLY+20)

#define ID_SPRITE_MARIO_TAIL_WORLDMAP (ID_SPRITE_MARIO_TAIL+990)


#pragma endregion 

#define ID_SPRITE_BRICK 20000
#define ID_SPRITE_QUESTION_BRICK 21000
#define ID_SPRITE_SPECIAL_BRICK 22000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_GROUND 50000


#define ID_SPRITE_BACKGROUND_TILE 11000

#define ID_SPRITE_PIPE 12000

#define ID_SRPITE_MUSHROOM 13000

#define ID_SPRITE_LEAF	14000

#define ID_SPRITE_FIREVENUSTRAP 15000

#define ID_SPRITE_FIREBALL 16000

#define ID_SPRITE_KOOPA 18000

#define ID_SPRITE_BUTTON 17000

#define ID_SPRITE_CARD 19000


///world map
#define ID_SPRITE_LANSCAPE	25000

#define ID_SPRITE_PATH 35000